# Generated by Django 3.2.3 on 2021-05-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objects_detected', models.CharField(max_length=100)),
                ('latency', models.CharField(max_length=100)),
                ('fps', models.CharField(max_length=100)),
                ('accuracy', models.CharField(max_length=100)),
            ],
        ),
    ]
